### ISSUE TITLE
Tried to start the containers

### ISSUE THREAD

**Issue by kehusa** [kevoree/xp-scaling#1]
@maxleiko Do you have any idea what went wrong?

knuteilif@knuteilif-VirtualBox:~/HEADS/docker/xp-scaling$ docker-compose upCreating network "xpscaling_default" with the default driver
Creating xpscaling_kevoree-client0_1
Creating xpscaling_kevoree-master_1
Creating xpscaling_kevoree-client2_1
Creating xpscaling_kevoree-client4_1
Creating xpscaling_kevoree-client3_1
Creating xpscaling_kevoree-client1_1
Attaching to xpscaling_kevoree-client0_1, xpscaling_kevoree-master_1, xpscaling_kevoree-client2_1, xpscaling_kevoree-client4_1, xpscaling_kevoree-client1_1, xpscaling_kevoree-client3_1
kevoree-master_1   | 15:57:33  ALL    KevoreeLogger    Set logLevel= info
kevoree-client2_1  | 15:57:33  ALL    KevoreeLogger    Set logLevel= info
kevoree-client0_1  | 15:57:33  ALL    KevoreeLogger    Set logLevel= info
kevoree-client3_1  | 15:57:33  ALL    KevoreeLogger    Set logLevel= info
kevoree-client4_1  | 15:57:33  ALL    KevoreeLogger    Set logLevel= info
kevoree-client1_1  | 15:57:33  ALL    KevoreeLogger    Set logLevel= info
kevoree-client1_1  | 15:57:33  ERROR  NodeJSRuntime    Unable to load Kevoree JSON model: (intermediate value)(intermediate value)(intermediate value).contains_za3rmp$ is not a function
kevoree-client1_1  | 15:57:33  ERROR  NodeJSRuntime    Platform shut down.
kevoree-client0_1  | 15:57:33  ERROR  NodeJSRuntime    Unable to load Kevoree JSON model: (intermediate value)(intermediate value)(intermediate value).contains_za3rmp$ is not a function
kevoree-client0_1  | 15:57:33  ERROR  NodeJSRuntime    Platform shut down.
kevoree-client0_1  | 15:57:33  ERROR  NodeJSRuntime    TypeError: Cannot read property 'metaClassName' of null
kevoree-client3_1  | 15:57:33  ERROR  NodeJSRuntime    Unable to load Kevoree JSON model: (intermediate value)(intermediate value)(intermediate value).contains_za3rmp$ is not a function
kevoree-client3_1  | 15:57:33  ERROR  NodeJSRuntime    Platform shut down.
kevoree-client0_1  |     at Kotlin.defineRootPackage.org.Kotlin.definePackage.kevoree.Kotlin.definePackage.modeling.Kotlin.definePackage.api.Kotlin.definePackage.ModelCloner.Kotlin.createClass.cloneModelElem (/usr/local/lib/node_modules/kevoree-nodejs-runtime/node_modules/kevoree-library/kevoree-library.js:26859:65)
kevoree-client0_1  |     at Kotlin.defineRootPackage.org.Kotlin.definePackage.kevoree.Kotlin.definePackage.modeling.Kotlin.definePackage.api.Kotlin.definePackage.ModelCloner.Kotlin.createClass.clone_2 (/usr/local/lib/node_modules/kevoree-nodejs-runtime/node_modules/kevoree-library/kevoree-library.js:26870:41)
kevoree-client0_1  |     at Kotlin.defineRootPackage.org.Kotlin.definePackage.kevoree.Kotlin.definePackage.modeling.Kotlin.definePackage.api.Kotlin.definePackage.ModelCloner.Kotlin.createClass.clone_1 (/usr/local/lib/node_modules/kevoree-nodejs-runtime/node_modules/kevoree-library/kevoree-library.js:26852:29)
kevoree-client0_1  |     at Kotlin.defineRootPackage.org.Kotlin.definePackage.kevoree.Kotlin.definePackage.modeling.Kotlin.definePackage.api.Kotlin.definePackage.ModelCloner.Kotlin.createClass.clone (/usr/local/lib/node_modules/kevoree-nodejs-runtime/node_modules/kevoree-library/kevoree-library.js:26849:29)
kevoree-client4_1  | 15:57:33  ERROR  NodeJSRuntime    Unable to load Kevoree JSON model: (intermediate value)(intermediate value)(intermediate value).contains_za3rmp$ is not a function
kevoree-client0_1  |     at KevoreeCore.stop (/usr/local/lib/node_modules/kevoree-nodejs-runtime/node_modules/kevoree-core/kevoree-core.js:76:28)
kevoree-client0_1  |     at NodeJSRuntime.stop (/usr/local/lib/node_modules/kevoree-nodejs-runtime/lib/NodeJSRuntime.js:110:20)
kevoree-client0_1  |     at errorHandler (/usr/local/lib/node_modules/kevoree-nodejs-runtime/cli.js:103:17)
kevoree-client0_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/kevoree-nodejs-runtime/cli.js:174:17)
kevoree-client0_1  |     at Module._compile (module.js:541:32)
kevoree-client0_1  |     at Object.Module._extensions..js (module.js:550:10)

**Comment by maxleiko** [comment]
Is it happening every time you try to test the xp ?
Did you update the `kevoree/js:latest` image (just to be sure?)  
Could you paste here the `.kevs` and `.yml` files ?
